### ISSUE TITLE
Invalid configurationapp.js:2942:13

### ISSUE THREAD

**Issue by antoniopinarella** [jwplayer/jwplayer-cast-receiver#17]
i have set it up like README told me, but cant get it working.
how to solve this?

> Invalid configurationapp.js:2942:13
> <anonymous>app.js:2942
> (Async: promise callback) <anonymous>app.js:2934
> <anonymous>
![image](https://cloud.githubusercontent.com/assets/13823786/25567880/7d25d2c2-2df7-11e7-8155-e6f5efbef42b.png)

thanks

**Comment by hussam-i-am** [comment]
Hi @antoniopinarella, looks like this is a valid issue, I will provide a fix for this by the end of next week.

**Comment by hussam-i-am** [comment]
@antoniopinarella Sorry for the delay, created the PR, should be working once its been merged.
