### ISSUE TITLE
W/MediaControlChannel: Message is malformed (No value for level)

### ISSUE THREAD

**Issue by tonyofrancis** [jwplayer/jwplayer-cast-receiver#21]
Hello @robwalch 
We have been using the jwplayer-cast-receiver and It has been working great until recently.Here is the behavior we are experiencing. Thanks for your help.

**Issue:**
 Android sender cast app does not receive properly formatted message from the receiver app causing the Android sender app to not show the miniContntrollerFragment, notification,  or receiver playback events.

**Error Received on Android Sender**
`W/MediaControlChannel: Message is malformed (No value for level); ignoring:`
```json
 {
        "type": "MEDIA_STATUS",
        "requestId": 0,
        "status": [{
                "type": "MEDIA_STATUS",
                "mediaSessionId": 7,
                "media": {
                        "contentId": "REMOVED FOR SECURITY REASONS",
                        "streamType": "BUFFERED",
                        "contentType": "application/json",
                        "metadata": {
                                "metadataType": 1,
                                "images": [{
                                        "url": "REMOVED FOR SECURITY REASONS",
                                        "width": 0,
                                        "height": 0
                                }],
                                "title": "REMOVED FOR SECURITY REASONS",
                                "subtitle": "REMOVED FOR SECURITY REASONS"
                        },
                        "duration": 4738,
                        "customData": {}
                },
                "playbackRate": 1,
                "playerState": "PLAYING",
                "currentTime": 222.890929,
                "supportedMediaCommands": 463,
                "volume": {},
                "activeTrackIds": [],
                "customData": {},
                "sessionId": "REMOVED FOR SECURITY REASONS",
                "senderName": "android"
        }]
}
```

It seems that the volume object in the JSON returned by the receiver app is missing the `level` and `muted` fields.
Casting on the app have been working up until recently. No code changes to both sender and receiver app in the last 3 months. The receiver app does not throw any errors in logs.

**Which version of the Cast SDK are you using?**
- Android Sender App is using : com.google.android.gms:play-services-cast-framework:11.6.0
- Custom Receiver app is using:  www.gstatic.com/cast/sdk/libs/receiver/2.0.0/cast_receiver.js

**On which version(s) of the OS (iOS, Android) do you observe the problem?**
- On All Android versions that support casting

**On which device type(s) such as phones, tablets or laptops (iPad, iPhone, etc.) do you observe the problem**
- Android Phones and Tablets

**Do you observe the problem when running on a physical device, or the simulator, or both**
- Physical device

**Comment by robwalch** [comment]
The mobile sender examples were provided "as-is". It looks like we are going to remove them as they are not being actively maintained.
